### PR TITLE
Added Badges & Support for Coveralls

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- Coveralls support added

@jackmellis : These are the following steps you need to do:

1. goto [Travis CI](https://travis-ci.org/) and enable this repo
2. goto [Coveralls](https://coveralls.io/) and enable this repo
3. release a newer version on [npm](https://www.npmjs.com/package/require-extension-hooks-vue) & [github](https://github.com/jackmellis/require-extension-hooks-vue/releases)

Only then you'd be able to see the badges like this:
Screenshot 2019-04-15 at 7 27 02 PM

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
- travis: https://travis-ci.org/vinayakkulkarni/require-extension-hooks-vue
- coveralls: https://coveralls.io/github/vinayakkulkarni/require-extension-hooks-vue

**Comment by vinayakkulkarni** [comment]
ping 🛎

**Comment by vinayakkulkarni** [comment]
💫

**Comment by vinayakkulkarni** [comment]
🔔

**Comment by jackmellis** [comment]
sorry for the delay! Could you fix merge conflicts and I will get this in

**Comment by vinayakkulkarni** [comment]
> sorry for the delay! Could you fix merge conflicts and I will get this in

There aren't any conflicts.
Screenshot 2019-04-30 at 11 57 05 AM

**Comment by vinayakkulkarni** [comment]
@jackmellis I've updated `nyc` which fixes the vulnerability: 
```
  High            Prototype Pollusion                                           
                                                                                
  Package         handlebars                                                    
                                                                                
  Patched in      >=4.0.13                                                      
                                                                                
  Dependency of   nyc [dev]                                                     
                                                                                
  Path            nyc > istanbul-reports > handlebars                           
                                                                                
  More info       https://npmjs.com/advisories/755      
```

Also, had to update the ava `setup` due to an open issue in vue-test-utils - https://github.com/vuejs/vue-test-utils/issues/936 to make the tests work

Can you please check and revert? 
Thanks.

**Comment by vinayakkulkarni** [comment]
Bump

**Comment by vinayakkulkarni** [comment]
@jackmellis you there?

**Comment by jackmellis** [comment]
weird, github is still telling me there are merge conflicts...
image

**Comment by vinayakkulkarni** [comment]
@jackmellis I've sent a new PR  #39 without the previously merged commits, maybe that was causing the merge conflicts issue?

**Comment by vinayakkulkarni** [comment]
Bump 🛎

**Pull request closed without merging**
